// Generated by Dagger (https://dagger.dev).
package com.example.nagwatask.presentation.file.fragment.adapter;

import dagger.internal.Factory;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class FilesAdapter_Factory implements Factory<FilesAdapter> {
  @Override
  public FilesAdapter get() {
    return newInstance();
  }

  public static FilesAdapter_Factory create() {
    return InstanceHolder.INSTANCE;
  }

  public static FilesAdapter newInstance() {
    return new FilesAdapter();
  }

  private static final class InstanceHolder {
    private static final FilesAdapter_Factory INSTANCE = new FilesAdapter_Factory();
  }
}
